import { ArtItem } from "./artItems";

export const yeezusItems: ArtItem[] = [
  {
    era: "Yeezus",
    name: "Yeezus",
    notes:
      "This minimalist cover displays a CD with red tape on the side, appearing like many bargain bin disks would. One of Kanye's major influences going into the project was his newfound love of minimalist art. This minimalism is a stark contrast with his last album My Beautiful Dark Twisted Fantasy, which had 5 different covers and the whole album being an artistic statement. This album had a minimalist approach to it and Kanye's influences and the cover represent that.",
    designer: "Joe Perez & Virgil Abloh",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Used",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Alternate Cover 1]",
    notes:
      "Revealed as the art to Yeezus and changed shortly before release. Includes similar elements to the final cover like the jewel case, as well as additional graphics and a melted face that's meant to be Kanye's melted cruciffix taking the form of Jesus.",
    designer: "Meredith Truax",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Alternate",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Alternate Cover 2]",
    notes:
      "Second cover seen in official advertisements right before release. Almost identical to the final cover, but the red tape is still the duct tape version seen on the previous cover and various concept art.",
    designer: "Joe Perez & Virgil Abloh",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Alternate",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Animated Cover 3]",
    notes:
      "Posted by opt_archive on Instagram. Actually a gif. Dated May 16th, 2013.",
    designer: "Joe Perez",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 9]",
    notes:
      "The gold is supposed to be Kanye's melted gold crucifix. If you look closely, there seems to be a face being torn from another face (left, right). Made in May 2013.",
    designer: "Joe Perez",
    artType: "",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 10]",
    notes: "Posted by opt_archive on Instagram. Made in May 2013.",
    designer: "Joe Perez",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 12]",
    notes: "Posted by opt_archive on Instagram. Made in May 2013.",
    designer: "Joe Perez",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 12]",
    notes: "Posted by opt_archive on Instagram. Made in May 2013.",
    designer: "Joe Perez",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 13]",
    notes:
      "Another alternate cover for Yeezus. Has the My Beautiful Dark Twisted Fantasy art Kanye held on chains. Leaked September 26th, 2023. ",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 14]",
    notes: "Another alternate cover for Yeezus. Leaked September 26th, 2023.",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 15]",
    notes: "Another alternate cover for Yeezus. Leaked September 26th, 2023.",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 16]",
    notes:
      "Another early Yeezus cover featuring art by George Condo. Dated May 22nd, 2013.",
    designer: "Joe Perez & George Condo",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 17]",
    notes:
      "An early Yeezus cover featuring art by George Condo. Dated May 23rd, 2013.",
    designer: "Joe Perez & George Condo",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 18]",
    notes: "Posted by opt_archive on Instagram. Dated May 24th, 2013.",
    designer: "Joe Perez",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 19]",
    notes:
      "Posted by parisaintboutique on Instagram. Similar to the final cover, but has red tape in the middle with Yeezus written on it twice. ",
    designer: "Kanye West & Virgil Abloh",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 20]",
    notes: "Another alternate cover for Yeezus. Leaked September 26th, 2023.",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 21]",
    notes:
      "Another alternate cover for Yeezus. Similar to the release cover, but the CD is alot less shiny and there is text on it. Leaked September 26th, 2023. ",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 22]",
    notes:
      "Another alternate cover for Yeezus. Very similar to release, but has a bloomy effect with rays. Leaked September 26th, 2023.",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 23]",
    notes:
      "Cover shown in Virgil Abloh's 2019 book Figures of Speech. Image shown here is a recreation.",
    designer: "George Condo & Virgil Abloh",
    artType: "Recreation",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 24]",
    notes:
      "Cover shown in Virgil Abloh's 2019 book Figures of Speech. Image shown here is a recreation.",
    designer: "George Condo & Virgil Abloh",
    artType: "Recreation",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 25]",
    notes:
      "Cover shown in Virgil Abloh's 2019 book Figures of Speech. Image shown here is a recreation.",
    designer: "George Condo & Virgil Abloh",
    artType: "Recreation",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 26]",
    notes:
      "Cover shown in Virgil Abloh's 2019 book Figures of Speech. Image shown here is a recreation.",
    designer: "George Condo & Virgil Abloh",
    artType: "Recreation",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 27]",
    notes:
      "Cover shown in Virgil Abloh's 2019 book Figures of Speech. Image shown here is a recreation.",
    designer: "George Condo & Virgil Abloh",
    artType: "Recreation",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Animated Cover 4]",
    notes: "Another animated cover. Also a gif.",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Cover 28]",
    notes:
      "Cover shown in Virgil Abloh's 2019 book Figures of Speech. Image shown here is a recreation.",
    designer: "Virgil Abloh",
    artType: "Recreation",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Rough Draft Covers Book]",
    notes:
      "Virgil Abloh showed off many unused covers and concept art for Yeezus in his 2019 book Figures of Speech.",
    designer: "Virgil Abloh",
    artType: "Scan",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Vinyl Concept Art]",
    notes: "Unused vinyl concept art for Yeezus designed by LUCKYME.",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Concept Art",
    use: "Concept Art",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Promo]",
    notes:
      "Promotion photo for Yeezus. Has 'On Sight' spelled as 'On Site' & has 'Hold My Liquor' named as 'Can't Hold My Liquor'. Leaked September 26th, 2023.",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Promo Art",
    use: "Unused",
  },
  {
    era: "Yeezus",
    name: "Yeezus [Banner]",
    notes: "Banner used on the iTunes page for Yeezus.",
    designer: "Jim Joe",
    artType: "Digital",
    projectType: "Other",
    use: "Used",
  },
  {
    era: "Yeezus",
    name: "Yeezus [iTunes Promo Banner]",
    notes: "Banner used on iTunes to promote Yeezus.",
    designer: "Jim Joe",
    artType: "Digital",
    projectType: "Promo Art",
    use: "Used",
  },
  {
    era: "Yeezus",
    name: "White Dress",
    notes:
      "Extremely similar to most of the singles released for Cruel Summer, but this time the artist name is above the song name and the song name is in white. ",
    designer: "Joe Perez & Virgil Abloh",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Used",
  },
  {
    era: "Yeezus",
    name: "The WRLDFMS Tony Williams - Another You (Remix)\n(feat. Kanye West, King Chip & Freddie Gibbs)",
    notes:
      "Cover art for the The WRLDFMS Tony Williams single 'Another You (Remix)', featuring Kanye West, King Chip and Freddie Gibbs.",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Used",
  },
  {
    era: "Yeezus",
    name: "Lil Wayne - I Am Not A Human Being II",
    notes:
      "Lil Wayne announced in November of 2012 that Kanye was designing the cover art and packaging for his album I Am Not A Human Being II. The cover officially debuted on January 30th, 2013. Lil Wayne explained the cover by saying, 'he chose the moth butterfly thing because it has so many different stages of life, and it goes through so many forms and changes, and no one can figure it out, and it's always beautiful'.",
    designer: "Kanye West / Joe Perez",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Used",
  },
  {
    era: "Yeezus",
    name: "Lil Wayne - I Am Not A Human Being II [Outside Packaging]",
    notes:
      "Lil Wayne announced in November of 2012 that Kanye was designing the cover art and packaging for his album I Am Not A Human Being II. This the outer packaging from the cardboard sleeve version of the CD.",
    designer: "Kanye West / Joe Perez",
    artType: "Digital",
    projectType: "Physical Packaging",
    use: "Used",
  },
  {
    era: "Yeezus",
    name: "Lil Wayne - I Am Not A Human Being II [Inside Packaging]",
    notes:
      "Lil Wayne announced in November of 2012 that Kanye was designing the cover art and packaging for his album I Am Not A Human Being II. This the inner packaging from the cardboard sleeve version of the CD.",
    designer: "Kanye West / Joe Perez",
    artType: "Digital",
    projectType: "Physical Packaging",
    use: "Used",
  },
  {
    era: "Yeezus",
    name: "Lil Wayne - I Am Not A Human Being II [Animated Cover]",
    notes:
      "Lil Wayne announced in November of 2012 that Kanye was designing the cover art and packaging for his album I Am Not A Human Being II. On the day of the albums release an animated cover was released. Actually a gif. Show's the red moth from the album cover flying into frame and then narrowly escaping being eaten by a giant cloud skull thing.",
    designer: "Kanye West / Joe Perez",
    artType: "",
    projectType: "Front Cover",
    use: "Used",
  },
  {
    era: "Yeezus",
    name: "Lil Wayne - Love Me\n(feat. Drake & Future)",
    notes: "Single artwork designed by Kanye West.",
    designer: "Kanye West",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Used",
  },
  {
    era: "Yeezus",
    name: "Rihanna - Diamonds (Remix)\n(feat. Kanye West)",
    notes:
      "Cover art for the Rihanna single 'Diamonds (Remix)' featuring Kanye West.",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Used",
  },
  {
    era: "Yeezus",
    name: "The Game - Rollin'\n(feat. Kanye West, Trae tha Truth, Z-Ro, Paul Wall & Slim Thug)",
    notes:
      "Official cover art to the song 'Rollin'' by The Game, which featured Kanye West.",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Used",
  },
];
