import { ArtItem } from "./artItems";

export const yeezus2Items: ArtItem[] = [
  {
    era: "Yeezus 2",
    name: "Lost Yeezus",
    notes: "Posted by opt_archive on Instagram.",
    designer: "Joe Perez",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus 2",
    name: "Yeezus 2 [Rough Draft Cover 1]",
    notes: "Posted by opt_archive on Instagram.",
    designer: "Joe Perez",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus 2",
    name: "Yeezus 2 [Rough Draft Cover 2]",
    notes: "Posted by opt_archive on Instagram.",
    designer: "Joe Perez",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus 2",
    name: "Yeezus 2 [Rough Draft Cover 3]",
    notes: "Posted by opt_archive on Instagram.",
    designer: "Joe Perez",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus 2",
    name: "Yeezus 2 [Rough Draft Cover 4]",
    notes: "Posted by opt_archive on Instagram.",
    designer: "Joe Perez",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus 2",
    name: "Yeezus 2 [Rough Draft Cover 5]",
    notes: "Posted by opt_archive on Instagram.",
    designer: "Joe Perez",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus 2",
    name: "Yeezus 2 [Rough Draft Cover 6]",
    notes:
      "Posted by opt_archive on Instagram, meant for Yeezus 2 as confirmed by Joe Perez himself on Instagram.",
    designer: "Joe Perez",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Unused",
  },
  {
    era: "Yeezus 2",
    name: "Busta Rhymes - Thank You (feat. Kanye West, Lil Wayne & Q-Tip)",
    notes:
      "Cover art for the Busta Rhymes single 'Thank You', featuring Kanye West, Lil Wayne and Q-Tip.",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Used",
  },
  {
    era: "Yeezus 2",
    name: "D'Banj - Scape Goat (The Fix) (feat. Kanye West)",
    notes:
      "Cover art for the D'Banj single 'Scape Goat (The Fix)', featuring Kanye West.",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Used",
  },
  {
    era: "Yeezus 2",
    name: "Future - I Won (feat. Kanye West)",
    notes: "Cover art for the Future single 'I Won', featuring Kanye West.",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Used",
  },
  {
    era: "Yeezus 2",
    name: "Future - I Won (Louis Futon Remix) (feat. Kanye West)",
    notes:
      "Cover art for the Louis Futon remix of Future's single 'I Won' featuring Kanye West.",
    designer: "Unknown",
    artType: "Digital",
    projectType: "Front Cover",
    use: "Used",
  },
];
